function Amber(a){return Amber.getBindable(a)}Amber.get=function(a){try{return Amber(a).get()}catch(b){return null}};Amber.bindables=[];Amber.option=function(a){return void 0==a?null:a};Amber.buildBindable=function(a){var b;if(a instanceof Array)for(b=0;b<a.length;b++)Amber.buildBindable(a[b]);else try{b=eval(a);var e=Amber.getBindable(a);if(null==e||e==Amber)Amber[a]=new Bindable(b,a,null)}catch(c){console.log("Failed to build bindable for "+a+":"+c.message)}};
Amber.getBindable=function(a){for(var b=a.split("."),e=Amber,c=0;c<b.length;c++){var f=e[b[c]];if(f instanceof Bindable)e=f;else if(e instanceof Bindable)if(e.isArray())e=e.getArrayBindable(b[c]);else return null;else break}if(e==Amber){if(e[a]instanceof Bindable)return e[a];for(c=b.length-1;0<c;c--){a="";for(f=0;f<c;f++)a+=b[f]+(f==c-1?"":".");if(e[a]instanceof Bindable){for(e=e[a];c<b.length;c++)if(e=e[b[c]],!(e instanceof Bindable))return null;break}}}return e};
Amber.parseInfo=function(a,b,e){var c=a.getAttribute(b);return null!=c&&c.startWith("@{")&&c.endWith("}")?(c=c.substr(2,c.length-3),null!=e&&(c=c.replace("[__var__]",e)),new BindingInfo(a,b,c)):null};
Amber.bindElem=function(a,b,e){if(a.hasAttribute("model"))Amber.bindModel(a,b);else{var c;if(a.hasAttribute("bind")&&0==$(a).parents("[model]").length){if(null==a.getAttribute("bind")||""==a.getAttribute("bind")){c=[];for(var f=0;f<a.attributes.length;f++){var d=a.attributes[f].name,k=a.getAttribute(d);k.startWith("@{")&&k.endWith("}")&&c.push(d)}a.setAttribute("bind",c.toString())}else c=a.getAttribute("bind").split(",");d=c.length;for(f=0;f<d;f++)try{var g=Amber.parseInfo(a,c[f],e);if(null!=g){var h,
k=[];if(g.refModel&&null==b)console.log("\u5143\u7d20\u4e0d\u5728\u6a21\u578b\u5143\u7d20\u4e2d\uff0c\u4e0d\u80fd\u5f15\u7528\u884c\u6570\u636e\u3002"+g.bindStr);else{null==b||g.refModel||b.addBindingInfo(g);h=Amber._procBindDataName(g.dataName,b);null!=h?k.push(h):console.log("\u6307\u5b9a\u7684\u7ed1\u5b9a\u6570\u636e\u4e0d\u6b63\u786e\uff1a"+g.bindStr);for(var m=g.params,l=0;null!=m&&l<m.length;l++)h=Amber._procBindDataName(m[l],b),null!=h?k.push(h):console.log("\u6307\u5b9a\u7684\u7ed1\u5b9a\u6570\u636e\u4e0d\u6b63\u786e\uff1a"+
g.bindStr);for(l=0;l<k.length;l++)h=k[l],h.addBindingInfo(g),$(g.elem).is("input")&&"checkbox"==g.elem.type&&"bind-checked"==g.attrName?Amber._setupCheckboxHandler(g.elem,h):$(g.elem).is("input")&&"radio"==g.elem.type&&"selected"==g.attrName?Amber._setupRadioHandler(g.elem,h):($(g.elem).is("textarea")||$(g.elem).is("input")&&("text"==g.elem.type||"password"==g.elem.type||"email"==g.elem.type))&&"value"==g.attrName?Amber._setupTextHandler(g.elem,h):$(g.elem).is("select")&&"selected"==g.attrName&&Amber._setupSelectHandler(g.elem,
h)}}}catch(r){console.log("\u5e94\u7528\u7ed1\u5b9a\u65f6\u51fa\u9519\uff0c\u7ed1\u5b9a\u4fe1\u606f\uff1a"+(null!=g?g.bindStr+"\u3002":"\u9519\u8bef\u3002")+r.description)}a.removeAttribute("bind");$(a).find("[bind]").each(function(){Amber.bindElem(this,b,e)})}}};Amber._procBindDataName=function(a,b){if(a.startWith("model")){if("model"==a)return b;var e=b._getBindable(a.substring(6));return e instanceof Bindable?e:null}return Amber.getBindable(a)};
Amber.bindModel=function(a,b,e){if(!a.hasAttribute("processed")){var c=a.getAttribute("model");if(c.startWith("model."))if(null!=b)c=b._getBindable(c.substr(6));else return;else c=Amber.getBindable(c);if(null!=c){c.addModel(a);if(c.isArray())for(var f=a,d=0,k=c.len();d<k;d++){b=c.get(d);var g=$(a).clone(!0).get(0);$(g).show();g.removeAttribute("model");$(g).data("modelElem",a);b.addRowElem(g);Amber.bindElem(g,b,e);$(f).after(g);f=g}$(a).hide();a.hasAttribute("removeModel")&&$(a).remove();a.setAttribute("processed",
"true")}}};Amber.bindElems=function(){$("[bind]").each(function(){Amber.bindElem(this)})};Amber._reservedProperties=["parent"];
Amber.apply=function(a,b){if(void 0==a)a=Amber;else if(a instanceof String||"string"==typeof a)a=Amber(a);if(a!=Amber&&a.isArray())for(var e=0;e<a._rows.length;e++)Amber.apply(a._rows[e],b);else for(var c=a._bindingInfos,f=null==c?0:c.length,e=0;e<f;e++){var d=c[e];if(d.elem!=b&&null!=d.bindStr&&null!=d.attrName)try{var k=a._attrName,g,h;if(""==k)d.refModel?d.dataName.startWith("model.")?(k=d.dataName.substring(6),h=a._getBindable(k)):(k=d.dataName,h=Amber.getBindable(k)):h=Amber.getBindable(d.dataName),
g=null==h?null:h.get();else if(!d.attrName.startWith("on")&&!d.attrName.startWith("event-on")&&null!=d.params&&0<d.params.length)if(d.refModel){var m=a;for(g=null;null!=m.parent;)if(m=m.parent,""==m._attrName){d.dataName.startWith("model.")?(k=d.dataName.substring(6),h=m._getBindable(k)):(k=d.dataName,h=Amber.getBindable(k));g=null==h?null:h.get();g=Amber._getDataValue(d,g,m,h.parent);break}}else h=Amber.getBindable(d.dataName),g=null==h?null:h.get();else h=a,g=a.get();var l;l=null==g?void 0:d.attrName.startWith("on")||
d.attrName.startWith("event-on")?g:Amber._getDataValue(d,g,a,h.parent);if($(d.elem).is("input")||"text"!=d.attrName)if($(d.elem).is("input")||"html"!=d.attrName)if($(d.elem).is("input")&&"checkbox"==d.elem.type&&"bind-checked"==d.attrName)d.elem.checked=l;else if($(d.elem).is("input")&&"radio"==d.elem.type&&"selected"==d.attrName)d.elem.checked=l==d.elem.value;else if($(d.elem).is("select")&&"selected"==d.attrName)for(e=0;e<d.elem.options.length;e++){if(d.elem.options[e].selected=!1,d.elem.options[e].value==
l||-1!=$.inArray(d.elem.options[e].value,l))d.elem.options[e].selected=!0}else if(d.attrName.startWith("on")||d.attrName.startWith("event-on")){if(g instanceof Function){var r=d.attrName.startWith("on")?d.attrName.substr(2):d.attrName.substr(8),m=null;if(d.refModel)if(""==a._attrName)m=a;else for(var n=a;null!=n.parent;){if(n=n.parent,""==n._attrName){m=n;break}}else m=a;if(null!=m){var t=Amber._buildArgs(d,m);$(d.elem).off(r,Amber._eventHandler);$(d.elem).on(r,{func:g,thisArg:h.parent,bindable:m,
args:t},Amber._eventHandler)}}}else if(d.attrName.startWith("css-")){var u=d.attrName.substr(4);$(d.elem).css(u,l)}else d.elem[d.attrName]=void 0==l?"":l;else $(d.elem).html(l);else $(d.elem).text(l)}catch(s){console.error("\u5e94\u7528\u7ed1\u5b9a\u65f6\u51fa\u9519\uff0c\u7ed1\u5b9a\u4fe1\u606f\uff1a"+(null!=d?d.bindStr+"\u3002":"\u9519\u8bef\u3002")+s.description),console.error(s.stack)}}for(var q in a)0>Amber._reservedProperties.indexOf(q)&&!q.startWith("_")&&a.hasOwnProperty(q)&&a[q]instanceof
Bindable&&Amber.apply(a[q],b)};Amber.bindAll=function(a,b){a.hasAttribute("bind")?Amber.bindElem(a,void 0,b):$(a).find("[bind]").each(function(){Amber.bindElem(this,void 0,b)})};Amber.bind=function(a){null!=a?Amber.bindElem(a):Amber.bindElems();Amber.apply()};Amber._getDataValue=function(a,b,e,c){return b instanceof Function?Amber._execFunc(a,b,e,c):b};
Amber._execFunc=function(a,b,e,c){if(a.dataName.startWith("model."))try{var f=Amber._buildArgs(a,e);return b.apply(c,f)}catch(d){console.log("\u8c03\u7528\u51fd\u6570\u5931\u8d25\uff1a"+a.bindStr),console.error(d)}else try{return f=[e].concat(Amber._buildArgs(a,e)),b.apply(c,f)}catch(k){console.log("\u8c03\u7528\u51fd\u6570\u5931\u8d25\uff1a"+a.bindStr),console.error(k)}return null};
Amber._buildArgs=function(a,b){for(var e=[],c=null==a.params?[]:a.params,f=0;f<c.length;f++){var d=c[f];"model"==d?e.push(b):(d.startWith("model.")?(d=d.substring(6),d=b._getBindable(d)):d=Amber(d),e.push(d))}return e};Amber._setupTextHandler=function(a,b){$(a).bind("input propertychange",function(e){b.put(void 0,this.value,a)})};Amber._setupCheckboxHandler=function(a,b){$(a).is("input")&&"checkbox"==a.type&&$(a).bind("change",function(e){b.put(void 0,this.checked,a)})};
Amber._setupRadioHandler=function(a,b){$(a).is("input")&&"radio"==a.type&&$(a).bind("change",function(e){b.put(void 0,this.value,a)})};Amber._setupSelectHandler=function(a,b){$(a).is("select")&&$(a).bind("change",function(e){for(var c=(e=a.hasAttribute("multiple"))?[]:"",f=0;f<a.options.length;f++)if(a.options[f].selected)if(e)c.push(a.options[f].value);else{c=a.options[f].value;break}b.put(void 0,c,a)})};
Amber._eventHandler=function(a){var b=a.data.func,e=a.data.thisArg,c=a.data.args,c=[].concat(a.data.bindable,a,c);b.apply(e,c)};window.Amber=Amber;Amber.bind=Amber.bind;Amber.apply=Amber.apply;Amber.bindElem=Amber.bindElem;Amber.get=Amber.get;Amber.buildBindable=Amber.buildBindable;function Bindable(a,b,e,c){this._attrName=b;this._value=a;this._type="object";this._obj=null==e?window:e;this._models=[];this._rows;this._bindingInfos=[];this._rowElems=[];this.parent=c;if(null==this._obj)this._type="global";else if("function"==typeof a)this._type="function";else if($.isArray(a)){this._type="array";this._rows=Array(a.length);for(b=0;b<a.length;b++)this._rows[b]=new Bindable(a[b],"",a,this);for(p in a)$.isNumeric(p)||(this[p]=new Bindable(a[p],p,a,this))}else if("object"==typeof a)for(p in this._type=
"object",a)this[p]=new Bindable(a[p],p,a,this);else this._type="native"}Bindable.prototype.isReadOnly=function(){return"function"==this._type};Bindable.prototype.isFunction=function(){return"function"==this._type};Bindable.prototype.isArray=function(){return"array"==this._type};Bindable.prototype.isObject=function(){return"object"==this._type};Bindable.prototype.isNative=function(){return"native"==this._type};Bindable.prototype.isGlobal=function(){return"global"==this._type};
Bindable.prototype.len=function(){return this.isArray()?this._value.length:0};Bindable.prototype.addModel=function(a){this._models.push(a)};Bindable.prototype.removeModel=function(a){this._models.remove(a)};Bindable.prototype.addBindingInfo=function(a){this._bindingInfos.push(a)};Bindable.prototype.removeBindingInfo=function(a){this._bindingInfos.remove(a);a.clear()};
Bindable.prototype.remove=function(a){if(null==a){for(var b=this._bindingInfos.length-1;0<=b;b--)this.removeBindingInfo(this._bindingInfos[b]);for(b=this._rowElems.length-1;0<=b;b--)$(this._rowElems[b]).remove(),this._rowElems.remove(b);if(this.parent.isArray())for(b=0;b<this.parent._rows.length;b++)if(this.parent._rows[b]==this){this.parent._rows.remove(this);this.parent._obj[this.parent._attrName].remove(b);break}}else if(this.isArray())for(b=0;b<this._rows.length;b++)if(this._rows[b]==a){a=this._rows[b];
this._rows.remove(b);this._obj[this._attrName].remove(b);a.remove();break}};Bindable.prototype.removeAll=function(){if(this.isArray())for(var a=this._rows.length-1;0<=a;a--){var b=this._rows[a];this._rows.remove(a);this._obj[this._attrName].remove(a);b.remove()}};
Bindable.prototype.add=function(a){if(this.isArray()){this._obj[this._attrName].push(a);var b=this._rows[this._rows.length-1];a=new Bindable(a,"",this._obj,this);this._rows.push(a);for(var e,c,f,d=null==b?this._models:b._rowElems,k=0;k<d.length;k++)e=d[k],f=null==b?e:$(e).data("modelElem"),c=$(f).clone(!0).get(0),a.addRowElem(c),c.removeAttribute("model"),$(c).removeData(),$(c).data("modelElem",f),Amber.bindElem(c,a),$(e).after(c),$(c).show(100);Amber.apply(a,void 0)}};
Bindable.prototype.addRowElem=function(a){this._rowElems.push(a)};Bindable.prototype.getArrayBindable=function(a){return this.isArray()&&$.isNumeric(a)&&parseInt(a)<this._rows.length?this._rows[parseInt(a)]:null};Bindable.prototype.setAttr=function(a){this[a]=new Bindable(this.get()[a],a,this.get(),this)};
Bindable.prototype.get=function(a){void 0==a&&(a=this._attrName);if(this.isArray())if($.isNumeric(a)){if(a=parseInt(a),0<=a&&a<=this.len())return this._rows[a]}else return this._obj[a];else{if(this.isObject())return this[a]instanceof Bindable?this[a]._obj[a]:""==a?this._value:getAttr(this._obj,a);if(this.isNative())return this._obj[a];if(this.isFunction())return void 0==this[a]?this._obj[a]:this[a]}return null};
Bindable.prototype.put=function(a,b,e){1==arguments.length&&(b=arguments[0],a=this._attrName);void 0==a&&(a=this._attrName);var c;c=a!=this._attrName||this.isNative()||this.isFunction()?this._getBindable(a):this;if(c instanceof Bindable)if(c.isNative()||c.isFunction())c.put(a,b);else if(c.isArray()){if(b instanceof Array){var f=c.len(),d=b.length;Math.min(f,d);for(f-=1;0<=f;f--){var k=c.getArrayBindable(f);null!=k&&c.remove.call(k)}for(f=0;f<d;f++)c.add(b[f])}}else{if(c.isObject())for(d in c)this.isNativeAttr(d)||
c.put(d,b[d])}else{if(!this.isFunction()||b instanceof Function)this._obj[a]=b;Amber.apply(this,e)}return this};Bindable.prototype.apply=function(a){Amber.apply(this,a)};Bindable.prototype.elements=function(){if(this.isArray()){for(var a=[],b=0;b<this._rows;b++)a.push(this._rows[b].elements());return a}if(null!=this._rowElems&&0<this._rowElems.length)return this._rowElems;a=[];for(b=0;b<this._bindingInfos;b++)a.push(this._bindingInfos[b].elem);return a};
Bindable.prototype.isNativeAttr=function(a){return 0<=Bindable._nativeAttr.indexOf(","+a+",")};Bindable.prototype.call=function(){this.isFunction()&&this.get().apply(this.parent,arguments)};Bindable.prototype._getBindable=function(a){if(a instanceof Array){for(var b=this,e=0;e<a.length;e++){var c=a[e],f=b[c];if(null==f)if(b instanceof Bindable&&b.isArray())f=b.getArrayBindable(c);else return null;b=f}return b}a=a.split(".");return this._getBindable(a)};Bindable._nativeAttr=",_attrName,_value,_type,_obj,_models,_rows,_bindingInfos,parent,_rowElems,_selectedProduct,";
for(var p in Bindable.prototype)Bindable._nativeAttr+=p+",";window.Bindable=Bindable;Bindable.prototype.elements=Bindable.prototype.elements;function BindingInfo(a,b,e){this.elem=Amber.option(a);this.attrName=Amber.option(b);this.dataName=this.bindStr=Amber.option(e);this.params=null;this.refModel=!1;-1!=this.bindStr.indexOf("$")&&(this.dataName=this.bindStr.prefix("$"),this.params=this.bindStr.postfix("$").split(","));this.dataName.startWith("model")&&(this.refModel=!0);for(a=0;null!=this.params&&a<this.params.length;a++)b=this.params[a].trim(),b.startWith("model")&&(this.refModel=!0),this.params[a]=b}
BindingInfo.prototype.clear=function(){this.bindStr=this.attrName=null;$(this.elem).remove()};
